[package]
name = "svg-icon-check"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
resvg = "0.44.0"
usvg = "0.44.0"
tiny-skia = "0.11.4"  
image = "0.25.0"
anyhow = "1.0"
